version: "3.8"
services:
  scrape:
    build: .
    image: israeli-firefly-iii-scraper
    env_file: .env
    environment:
      PUPPETEER_ARGS: --no-sandbox
    entrypoint: firefly-iii-scraper
    volumes:
      - .scraper:/tmp/scraper